
project:
  type: book

format:
  html:
    theme: cosmo

book:
  title: "How to Code a Book"
  author:
    name: "Timothy Pratley"
  chapters:
    - ../docs/index.md
    - ../docs/chapter/c01_setup.md
    - ../docs/chapter/c01_choices.qmd
