---
dirs: [notebooks]
output-dir: docs
format: all
evaluator: clojure

---

<style>
.printedClojure .sourceCode {
  background-color: transparent;
  border-style: none;
}
</style>
# Babashka notebooks

Babashka is, by design, as close to Clojure as possible.

## Basic Examples

```clojure
(+ 1 2)
```
<div class="printedClojure">
```clojure
3

```
</div>

```clojure
{:x (range 3)}
```
<div class="printedClojure">
```clojure
{:x (0 1 2)}

```
</div>

## Hiccup

```clojure
^:kind/hiccup
[:div {:style {:background-color "#effeef"}}
 [:big [:big 3]]]
```
<div style="background-color:#effeef;"><big><big>3</big></big></div>
## Time

```clojure
(def now (java.time.ZonedDateTime/now))
```
<div>VAR#'scicloj.claykind.publish/now</div>
```clojure
(def LA-timezone (java.time.ZoneId/of "America/Los_Angeles"))
```
<div>VAR#'scicloj.claykind.publish/LA-timezone</div>
```clojure
(def LA-time (.withZoneSameInstant now LA-timezone))
```
<div>VAR#'scicloj.claykind.publish/LA-time</div>
```clojure
(def pattern (java.time.format.DateTimeFormatter/ofPattern "HH:mm"))
```
<div>VAR#'scicloj.claykind.publish/pattern</div>
```clojure
(.format LA-time pattern)
```
<div class="printedClojure">
```clojure
"10:49"

```
</div>

## Babashka vs clojure

##

The notable differences are:

* Code is evaluated with [Sci](https://github.com/babashka/SCI)
* Not all of Clojure is available
* Files start with a shell directive instead of a namespace

##

Did you know that Clojure treats `#!` as a comment?

##

So you can already create Babashka notebooks if you ignore the differences,
but this project (claykind) will detect Babashka and use Sci,
which will make it more directly compatible.

##

Would it be interesting thing to try is running claykind from babashka?
What possibilities does that open up?
Faster command-line blog generation?
