
project:
  type: book

format:
  html:
    theme:
      light: flatly
      dark: darkly

book:
  title: "Babashka Example Book"
  chapters:
    - index.md
    - chapters/bb.md
    - chapters/bb1.md
    - chapters/git-log-analysis.md
  twitter-card:
    creator: "@timothypratley"
  favicon: images/Clay.svg
  open-graph: true
